spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wildlife_mis
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        default_schema: public
#        jdbc:
#          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org:
#      springframework : DEBUG

#Local file store location
#fileUploadDirectory: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\wildlife-mis\src\main\resources\static\uploads
fileUploadDirectory: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\

#Server file store location
#fileUploadDirectory: /opt/tomcat/webapps/
server:
  port : 8082

MACInitializer:
  value: false
AppInitializer:
  value: false
CoverageLocationForHACAndARWithRangeService:
  value: false


#wildLife:
#  app:
#    jwtSecret: spring