
#Before deploying ot the the server check whether the cros origin is handle
#globally or controller level if globally then comment from controller level.


spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/wildlife_mis
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        default_schema: public
#        jdbc:
#          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true

#pdfUploadSize: 5*1024*1024
#imageUploadSize: 2*1024*1024

#        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org:
#      springframework : DEBUG



#Local file store location
#fileUploadDirectory: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\wildlife-mis\src\main\resources\static\uploads
fileUploadDirectoryForNotification: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\notification
fileUploadDirectoryForDocument: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\document
fileUploadDirectoryForGallery: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\gallery
fileUploadDirectoryForOfficial: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\official
fileUploadDirectoryForNGTCommittee: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\ngtCommittee

#Server file store location
#fileUploadDirectoryForNotification: /opt/tomcat/webapps/notification
#fileUploadDirectoryForDocument: /opt/tomcat/webapps/document
#fileUploadDirectoryForGallery: /opt/tomcat/webapps/gallery
#fileUploadDirectoryForOfficial: /opt/tomcat/webapps/official

server:
  port : 8083

MACInitializer:
  value: false
AppInitializer:
  value: false
CoverageLocationForHACAndARWithRangeService:
  value: false

  server:
    error:
      whitelabel:
        enabled: false

  management:
    endpoints:
      web:
        exposure:
          include: "*"
      health:
        show-details: always

  spring:
    mvc:
      problemdetails:
        enabled: true

#springdoc:
#  api-docs:
#    path: /wildlife-docs

#springdoc:
#  api-docs:
#    path: /api-docs swagger-ui/swagger-ui.html
#    enabled: true
#springdoc:
#  swagger-ui:
#    enabled : true
#    path : /swagger-ui.html
#    tryItOutEnabled : false
#    filter : false
#    syntaxHighlight:
#      activated : true
#wildLife:
#  app:
#    jwtSecret: spring