spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://localhost:5432/wildlife_mis
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        default_schema: public
#        jdbc:
#          batch_size: 100
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true

#pdfUploadSize: 5*1024*1024
#imageUploadSize: 2*1024*1024

#        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org:
#      springframework : DEBUG



#Local file store location
#fileUploadDirectory: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\wildlife-mis\src\main\resources\static\uploads
fileUploadDirectoryForNotification: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\notification
fileUploadDirectoryForDocument: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\document
fileUploadDirectoryForGallery: E:\WildlifeMIS(13-02-2024)\forest-wildlife-mis(15-02-2024)\wildlife-mis\gallery

#Server file store location
#fileUploadDirectoryForNotification: /opt/tomcat/webapps/notification
#fileUploadDirectoryForDocument: /opt/tomcat/webapps/document
#fileUploadDirectoryForGallery: /opt/tomcat/webapps/gallery

server:
  port : 8083

MACInitializer:
  value: false
AppInitializer:
  value: false
CoverageLocationForHACAndARWithRangeService:
  value: false


#wildLife:
#  app:
#    jwtSecret: spring